import { App, Component } from "vue";
import {
  ElTag,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElScrollbar,
  ElSubMenu,
  ElButton,
  ElButtonGroup,
  ElCol,
  ElRow,
  ElDivider,
  ElDropdown,
  ElMenu,
  ElMenuItem,
  ElDropdownItem,
  ElDropdownMenu,
  ElIcon,
  ElInput,
  ElPopover,
  ElPopper,
  ElTooltip,
  ElDrawer,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElBacktop,
  ElSwitch,
  ElCard,
  ElBadge,
  ElTabs,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElAvatar,
  ElEmpty,
  ElCollapse,
  ElCollapseItem,
  ElFormItem,
  ElForm,
  ElSelect,
  ElOption,
  ElSpace,
  ElCascader,
  ElCascaderPanel,
  ElAutocomplete,
  ElImage,
  // 指令
  ElLoading,
  ElInfiniteScroll,
  ElPagination,
  ElCheckbox,
  ElCheckboxGroup,
  ElCheckboxButton,
  ElCheckTag,
  ClickOutside,
  ElDialog,
  ElDatePicker,
  ElInputNumber,
  ElUpload,
  ElAlert,
  ElLink
} from "element-plus";

// Directives
const plugins = [ElLoading, ElInfiniteScroll];

const components = [
  ElTag,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElScrollbar,
  ElSubMenu,
  ElButton,
  ElButtonGroup,
  ElCol,
  ElRow,
  ElDivider,
  ElDropdown,
  ElMenu,
  ElMenuItem,
  ElDropdownItem,
  ElDropdownMenu,
  ElIcon,
  ElInput,
  ElPopover,
  ElPopper,
  ElTooltip,
  ElDrawer,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElBacktop,
  ElSwitch,
  ElBadge,
  ElTabs,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElCascader,
  ElCascaderPanel,
  ElForm,
  ElFormItem,
  ElSelect,
  ElOption,
  ElSpace,
  ElAvatar,
  ElEmpty,
  ElCard,
  ElCollapse,
  ElCollapseItem,
  ElPagination,
  ElAutocomplete,
  ElImage,
  ElCheckbox,
  ElCheckboxGroup,
  ElCheckboxButton,
  ElCheckTag,
  ElDialog,
  ElDatePicker,
  ElInputNumber,
  ElUpload,
  ElAlert,
  ElLink
];

export function useElementPlus(app: App) {
  // 注册组件
  components.forEach((component: Component) => {
    app.component(component.name, component);
  });
  // 注册指令
  plugins.forEach(plugin => {
    app.use(plugin);
  });
  app.directive("ClickOutside", ClickOutside);
}
