// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AliossFileLoad: typeof import('./plugins/kk-ui-kit/alioss/components/AliossFileLoad.vue')['default']
    AliossImagePreview: typeof import('./plugins/kk-ui-kit/alioss/components/AliossImagePreview.vue')['default']
    BaseTable: typeof import('./plugins/kk-ui-kit/components/base-table/BaseTable.vue')['default']
    ColumnSetting: typeof import('./plugins/kk-ui-kit/components/k-table/search/ColumnSetting.vue')['default']
    Demo: typeof import('./components/demo/index.vue')['default']
    HtmlToImage: typeof import('./components/HtmlToImage/index.vue')['default']
    KDialog: typeof import('./plugins/kk-ui-kit/components/k-dialog/KDialog.vue')['default']
    KForm: typeof import('./plugins/kk-ui-kit/components/k-form/KForm.vue')['default']
    KImageCrop: typeof import('./plugins/kk-ui-kit/components/k-image-crop/KImageCrop.vue')['default']
    KImageUpload: typeof import('./plugins/kk-ui-kit/components/k-image-upload/KImageUpload.vue')['default']
    KKAsyncExport: typeof import('./components/KKAsyncExport/index.vue')['default']
    KKAsyncImport: typeof import('./components/KKAsyncImport/index.vue')['default']
    KTable: typeof import('./plugins/kk-ui-kit/components/k-table/KTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCheckbox: typeof import('./plugins/kk-ui-kit/components/k-table/search/SearchCheckbox.vue')['default']
    SearchInput: typeof import('./plugins/kk-ui-kit/components/k-table/search/SearchInput.vue')['default']
    SearchRadio: typeof import('./plugins/kk-ui-kit/components/k-table/search/SearchRadio.vue')['default']
    SearchSelect: typeof import('./plugins/kk-ui-kit/components/k-table/search/SearchSelect.vue')['default']
    SearchSelectRemote: typeof import('./plugins/kk-ui-kit/components/k-table/search/SearchSelectRemote.vue')['default']
    SingleFileUpload: typeof import('./components/SingleFileUpload.vue')['default']
    UploadExcel: typeof import('./components/UploadExcel/UploadExcel.vue')['default']
  }
}

export {}
